engines:
  # disable Rubocop at CodeClimate, it cannot read the shared config from
  # the /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml file
  rubocop:
    enabled: false

  duplication:
    enabled: true
    config:
      languages:
      - ruby

ratings:
  paths:
  - "**.rb"
  - Rakefile
